# Generated by Django 6.0.6 on 2026-06-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome fantasia')),
                ('legal_name', models.CharField(max_length=180, verbose_name='razão social')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'corretora',
                'verbose_name_plural': 'corretoras',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=64, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_available', models.BooleanField(default=False, verbose_name='disponível para cadastro')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='brokerage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.brokerage', verbose_name='corretora'),
        ),
        migrations.AddField(
            model_name='brokerage',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brokerages', to='core.plan', verbose_name='plano'),
        ),
    ]
