# Generated by Django 6.0.6 on 2026-06-25 16:47

from django.db import migrations


DEFAULT_PLANS = [
    {
        'code': 'free',
        'name': 'Free',
        'description': 'Plano gratuito disponível para cadastro imediato.',
        'is_active': True,
        'is_available': True,
    },
    {
        'code': 'pro',
        'name': 'Pro',
        'description': 'Plano pago (em breve).',
        'is_active': True,
        'is_available': False,
    },
    {
        'code': 'business',
        'name': 'Business',
        'description': 'Plano empresarial pago (em breve).',
        'is_active': True,
        'is_available': False,
    },
]


def seed_plans(apps, schema_editor):
    Plan = apps.get_model('core', 'Plan')
    for data in DEFAULT_PLANS:
        Plan.objects.update_or_create(code=data['code'], defaults=data)


def remove_plans(apps, schema_editor):
    Plan = apps.get_model('core', 'Plan')
    Plan.objects.filter(code__in=[p['code'] for p in DEFAULT_PLANS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_brokerage_user_tenant'),
    ]

    operations = [
        migrations.RunPython(seed_plans, remove_plans),
    ]