# Generated by Django 6.0.6 on 2026-06-25 16:50 \
# Seeds the role ``Group``s defined in ``base.permissions.ROLE_CODES`` and \
# assigns each role the baseline Django permissions appropriate to it.

from django.db import migrations


def seed_role_groups(apps, schema_editor):
    """Create the role ``Group``s (names = role codes, e.g. ``brokerage_admin``).

    Baseline permission grants are applied by the ``post_migrate`` receiver in
    ``base.apps.BaseConfig.ready`` (see ``base.permissions.sync_role_permissions``)
    -- it runs after Django creates all ``ContentType`` / ``Permission`` rows so
    the lookups actually resolve.
    """
    from base.permissions import sync_roles
    sync_roles()


def remove_role_groups(apps, schema_editor):
    from base.permissions import ROLE_CODES
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=list(ROLE_CODES)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_custom_user_manager'),
    ]

    operations = [
        migrations.RunPython(seed_role_groups, remove_role_groups),
    ]