# Generated by Django 6.0.6 on 2026-06-26 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial_client'),
        ('core', '0005_seed_role_groups'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(blank=True, help_text='Número da apólice definido pela seguradora.', max_length=64, verbose_name='número')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='início da vigência')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim da vigência')),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='prêmio')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('vigente', 'Vigente'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('suspensa', 'Suspensa')], default='rascunho', max_length=32, verbose_name='status')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='resumo com IA')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='catalog.branch', verbose_name='ramo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client', verbose_name='cliente')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='catalog.insurancecompany', verbose_name='seguradora')),
                ('proposal', models.ForeignKey(blank=True, help_text='Proposta que originou a apólice, quando aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='proposals.proposal', verbose_name='proposta')),
            ],
            options={
                'verbose_name': 'apólice',
                'verbose_name_plural': 'apólices',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PolicyCoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('kind', models.CharField(choices=[('auto', 'Auto'), ('casa', 'Casa'), ('frota', 'Frota'), ('viagem', 'Viagem'), ('vida', 'Vida'), ('empresarial', 'Empresarial'), ('outros', 'Outros')], default='outros', help_text='Objeto segurado: auto, casa, frota, viagem, vida, empresarial, outros.', max_length=32, verbose_name='tipo')),
                ('description', models.CharField(blank=True, help_text='Descrição livre do objeto segurado.', max_length=255, verbose_name='descrição')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do objeto segurado.', max_digits=14, null=True, verbose_name='valor')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Atributos flexíveis em JSON (placa, endereço, lista de itens, destino, etc.).', verbose_name='atributos')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_items', to='policies.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'item coberto da apólice',
                'verbose_name_plural': 'itens cobertos da apólice',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['brokerage', 'id'], name='policies_po_brokera_26072a_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['brokerage', 'status'], name='policies_po_brokera_e7462b_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['brokerage', 'number'], name='policies_po_brokera_f064d3_idx'),
        ),
        migrations.AddIndex(
            model_name='policycovereditem',
            index=models.Index(fields=['brokerage', 'id'], name='policies_po_brokera_7abf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='policycovereditem',
            index=models.Index(fields=['brokerage', 'policy', 'id'], name='policies_po_brokera_376351_idx'),
        ),
    ]
