# Generated by Django 6.0.6 on 2026-07-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_role_groups'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(blank=True, help_text='Número do endosso definido pela seguradora.', max_length=64, verbose_name='número')),
                ('type', models.CharField(choices=[('alteracao', 'Alteração'), ('inclusao', 'Inclusão'), ('exclusao', 'Exclusão'), ('cancelamento', 'Cancelamento'), ('outros', 'Outros')], default='alteracao', max_length=32, verbose_name='tipo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='data de eficácia')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='policies.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'endosso',
                'verbose_name_plural': 'endossos',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['brokerage', 'id'], name='policies_en_brokera_d52f50_idx'), models.Index(fields=['brokerage', 'policy', 'id'], name='policies_en_brokera_18013b_idx'), models.Index(fields=['brokerage', 'effective_date'], name='policies_en_brokera_7793e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('renovada', 'Renovada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendente', max_length=32, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='policies.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'renovação',
                'verbose_name_plural': 'renovações',
                'ordering': ('due_date', '-id'),
                'indexes': [models.Index(fields=['brokerage', 'id'], name='policies_re_brokera_562e38_idx'), models.Index(fields=['brokerage', 'status'], name='policies_re_brokera_6ead6d_idx'), models.Index(fields=['brokerage', 'due_date'], name='policies_re_brokera_1b0078_idx'), models.Index(fields=['brokerage', 'policy', 'id'], name='policies_re_brokera_038bd9_idx')],
            },
        ),
    ]
