# Generated by Django 6.0.6 on 2026-06-29 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial_client'),
        ('core', '0005_seed_role_groups'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(blank=True, help_text='Número do sinistro definido pela seguradora.', max_length=64, verbose_name='número')),
                ('occurrence_date', models.DateField(blank=True, null=True, verbose_name='data da ocorrência')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('analise', 'Em análise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('pago', 'Pago')], default='aberto', max_length=32, verbose_name='status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='resumo com IA')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='clients.client', verbose_name='cliente')),
                ('covered_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policycovereditem', verbose_name='item coberto')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'sinistro',
                'verbose_name_plural': 'sinistros',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['brokerage', 'id'], name='claims_clai_brokera_3de43d_idx'), models.Index(fields=['brokerage', 'status'], name='claims_clai_brokera_25009b_idx'), models.Index(fields=['brokerage', 'policy', 'id'], name='claims_clai_brokera_488689_idx')],
            },
        ),
    ]
