# Generated by Django 6.0.6 on 2026-06-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_seed_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('first_name', models.CharField(max_length=150, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='sobrenome')),
                ('document', models.CharField(blank=True, help_text='CPF ou CNPJ do cliente. Apenas um por cliente.', max_length=32, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='resumo com IA')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['brokerage', 'id'], name='clients_cli_brokera_106a48_idx'), models.Index(fields=['brokerage', 'last_name', 'first_name'], name='clients_cli_brokera_6b62a8_idx')],
            },
        ),
    ]
