# Generated by Django 6.0.6 on 2026-06-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial_client'),
        ('core', '0005_seed_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('expirada', 'Expirada')], default='rascunho', max_length=32, verbose_name='status')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido até')),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='prêmio')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='resumo com IA')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='catalog.branch', verbose_name='ramo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='clients.client', verbose_name='cliente')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='catalog.insurancecompany', verbose_name='seguradora')),
            ],
            options={
                'verbose_name': 'proposta',
                'verbose_name_plural': 'propostas',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProposalCoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('kind', models.CharField(choices=[('auto', 'Auto'), ('casa', 'Casa'), ('frota', 'Frota'), ('viagem', 'Viagem'), ('vida', 'Vida'), ('empresarial', 'Empresarial'), ('outros', 'Outros')], default='outros', help_text='Objeto segurado: auto, casa, frota, viagem, vida, empresarial, outros.', max_length=32, verbose_name='tipo')),
                ('description', models.CharField(blank=True, help_text='Descrição livre do objeto segurado.', max_length=255, verbose_name='descrição')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do objeto segurado.', max_digits=14, null=True, verbose_name='valor')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Atributos flexíveis em JSON (placa, endereço, lista de itens, destino, etc.).', verbose_name='atributos')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_items', to='proposals.proposal', verbose_name='proposta')),
            ],
            options={
                'verbose_name': 'item coberto da proposta',
                'verbose_name_plural': 'itens cobertos da proposta',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['brokerage', 'id'], name='proposals_p_brokera_3c759d_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['brokerage', 'status'], name='proposals_p_brokera_ce51de_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalcovereditem',
            index=models.Index(fields=['brokerage', 'id'], name='proposals_p_brokera_786e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalcovereditem',
            index=models.Index(fields=['brokerage', 'proposal', 'id'], name='proposals_p_brokera_3eed20_idx'),
        ),
    ]
