# Generated by Django 6.0.6 on 2026-06-29 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial_client'),
        ('core', '0005_seed_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('is_default', models.BooleanField(default=False, help_text='Marque para usar este pipeline como padrão da corretora.', verbose_name='padrão')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'pipeline',
                'verbose_name_plural': 'pipelines',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('color', models.CharField(default='#2563eb', help_text='Cor hexadecimal (ex.: #2563eb).', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='cor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline', verbose_name='pipeline')),
            ],
            options={
                'verbose_name': 'etapa do pipeline',
                'verbose_name_plural': 'etapas do pipeline',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='fechamento previsto')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('ganha', 'Ganha'), ('perdida', 'Perdida'), ('abandonada', 'Abandonada')], default='aberta', max_length=32, verbose_name='status')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='resumo com IA')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client', verbose_name='cliente')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipelinestage', verbose_name='etapa')),
            ],
            options={
                'verbose_name': 'negociação',
                'verbose_name_plural': 'negociações',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['brokerage', 'id'], name='crm_pipelin_brokera_c8ab23_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['brokerage', 'id'], name='crm_pipelin_brokera_ed9d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['brokerage', 'pipeline', 'order'], name='crm_pipelin_brokera_42c23d_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['brokerage', 'id'], name='crm_deal_brokera_1df7de_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['brokerage', 'status'], name='crm_deal_brokera_2b3cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['brokerage', 'stage', 'id'], name='crm_deal_brokera_68e517_idx'),
        ),
    ]
