# Generated by Django 6.0.6 on 2026-06-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_seed_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'ramo',
                'verbose_name_plural': 'ramos',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='catalog.branch', verbose_name='ramo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'cobertura',
                'verbose_name_plural': 'coberturas',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('code', models.CharField(blank=True, help_text='Código interno ou identificador da seguradora.', max_length=64, verbose_name='código')),
                ('document', models.CharField(blank=True, help_text='CNPJ da seguradora.', max_length=32, verbose_name='CNPJ')),
                ('contact', models.CharField(blank=True, help_text='Descrição de contato (telefone/e-mail/representante).', max_length=255, verbose_name='contato')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'seguradora',
                'verbose_name_plural': 'seguradoras',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['brokerage', 'id'], name='catalog_bra_brokera_ed7e54_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['brokerage', 'name'], name='catalog_bra_brokera_505d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='coverage',
            index=models.Index(fields=['brokerage', 'id'], name='catalog_cov_brokera_f2177d_idx'),
        ),
        migrations.AddIndex(
            model_name='coverage',
            index=models.Index(fields=['brokerage', 'branch', 'id'], name='catalog_cov_brokera_e08254_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancecompany',
            index=models.Index(fields=['brokerage', 'id'], name='catalog_ins_brokera_5bfc75_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancecompany',
            index=models.Index(fields=['brokerage', 'name'], name='catalog_ins_brokera_24be41_idx'),
        ),
    ]
