# Generated by Django 6.0.6 on 2026-06-29 16:46

import attachments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_seed_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('object_id', models.PositiveIntegerField(verbose_name='id do objeto')),
                ('file', models.FileField(max_length=500, upload_to=attachments.models.attachment_path, verbose_name='arquivo')),
                ('name', models.CharField(help_text='Nome original do arquivo.', max_length=255, verbose_name='nome')),
                ('mime', models.CharField(blank=True, max_length=255, verbose_name='MIME')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo do objeto')),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['brokerage', 'id'], name='attachments_brokera_5f268a_idx'), models.Index(fields=['brokerage', 'content_type', 'object_id'], name='attachments_brokera_3163e2_idx')],
            },
        ),
    ]
