# Generated by Django 6.0.6 on 2026-07-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_seed_role_groups'),
        ('policies', '0002_endorsement_renewal'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='documento')),
                ('type', models.CharField(choices=[('pessoa', 'Pessoa'), ('empresa', 'Empresa')], default='pessoa', max_length=16, verbose_name='tipo')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de comissão do agente (0 a 100).', max_digits=5, verbose_name='percentual de comissão')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='contato')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'agente',
                'verbose_name_plural': 'agentes',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('document', models.CharField(blank=True, max_length=32, verbose_name='documento')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de comissão do produtor (0 a 100).', max_digits=5, verbose_name='percentual de comissão')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='contato')),
                ('agent', models.ForeignKey(blank=True, help_text='Agente parceiro. Deixe em branco se o produtor é direto da corretora.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='commercial.agent', verbose_name='agente')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'produtor',
                'verbose_name_plural': 'produtores',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor total')),
                ('brokerage_share', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='repasse corretora')),
                ('agent_share', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='repasse agente')),
                ('producer_share', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='repasse produtor')),
                ('reference_date', models.DateField(blank=True, help_text='Data usada nos filtros por período da tela de comissões.', null=True, verbose_name='data de referência')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commercial.agent', verbose_name='agente')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='policies.policy', verbose_name='apólice')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='proposals.proposal', verbose_name='proposta')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commercial.producer', verbose_name='produtor')),
            ],
            options={
                'verbose_name': 'comissão',
                'verbose_name_plural': 'comissões',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['brokerage', 'id'], name='commercial__brokera_bf255b_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['brokerage', 'name'], name='commercial__brokera_b6fa59_idx'),
        ),
        migrations.AddIndex(
            model_name='producer',
            index=models.Index(fields=['brokerage', 'id'], name='commercial__brokera_9127d4_idx'),
        ),
        migrations.AddIndex(
            model_name='producer',
            index=models.Index(fields=['brokerage', 'agent', 'id'], name='commercial__brokera_918e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', 'id'], name='commercial__brokera_0c5c04_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', 'agent', 'id'], name='commercial__brokera_92ae38_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', 'producer', 'id'], name='commercial__brokera_bcfc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', 'reference_date'], name='commercial__brokera_c259ea_idx'),
        ),
    ]
